apiVersion: apps/v1
kind: Deployment
metadata:
  name: serv2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serv2
  template:
    metadata:
      labels:
        app: serv2
    spec:
      containers:
      - name: serv2
        image: demo/serv2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8082

---

apiVersion: v1
kind: Service
metadata:
  name: serv2-service
spec:
  selector:
    app: serv2
  ports:
  - name: http
    port: 8082
    targetPort: 8082