apiVersion: apps/v1
kind: Deployment
metadata:
  name: serv3-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serv3
  template:
    metadata:
      labels:
        app: serv3
    spec:
      containers:
      - name: serv3
        image: demo/serv3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8083

---

apiVersion: v1
kind: Service
metadata:
  name: serv3-service
spec:
  selector:
    app: serv3
  ports:
  - name: http
    port: 8083
    targetPort: 8083
